### ISSUE TITLE
High CPU load for Solace-owned Threads

### ISSUE THREAD

**Issue by FWinkler79** [SolaceProducts/solace-spring-cloud#25]
With the latest version of the SCSt Binder Solace implementation we are realizing on thread in the application which usually has a more or less constant CPU load of 100%.
Debugging this issue, we realized that this thread seems to have been created by the solace binder:

```
"pool-3-thread-1@14886" prio=5 tid=0x2b nid=NA runnable
  java.lang.Thread.State: RUNNABLE
      at java.lang.Thread.isInterrupted(Thread.java:-1)
      at java.lang.Thread.isInterrupted(Thread.java:1038)
      at com.solace.spring.cloud.stream.binder.inbound.InboundXMLMessageListener.run(InboundXMLMessageListener.java:63)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
      at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
      at java.util.concurrent.FutureTask.run(FutureTask.java:-1)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
      at java.lang.Thread.run(Thread.java:834)
```

The output above is the dump of the thread that used up constant, high CPU load after we suspended it in the debugger. 
As you can see, it seems to be hosting the `com.solace.spring.cloud.stream.binder.inbound.InboundXMLMessageListener.run(InboundXMLMessageListener.java:63)` method. 

We are not sure what exactly causes the high CPU loads, but maybe you could have a look at the `run()` method and see if evth. is working as expected. Maybe it could `sleep()` every now and then, hoping to bring down CPU loads?

Thanks!

**Comment by Mrc0113** [comment]
Hi @FWinkler79, 

Can you share what version you're of `solace-spring-cloud` and/or `spring-cloud-stream-solace-binder` that you're specifying in the pom? I think you may be running into #20 which we fixed in `v1.1.1` of `solace-spring-cloud`. It has only been available on mvn central for about a week now.

**Comment by FWinkler79** [comment]
Thank you @Mrc0113!
Indeed, we were still on v1.1.0. 
We will try it out and confirm with the new version, but I think I will close this issue then.

**Comment by Nephery** [comment]
Seems like this is already a resolved issue so I'll go ahead and close this. @FWinkler79 if this is still a problem, let us know and we can reopen this issue.
